site_name: "TPI API"
docs_dir: mk_docs
site_dir: site

markdown_extensions:
  - footnotes

extra_css:
  - assets/stylesheets/extra.css

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tabs            
    - content.tabs.link       
  language: en
  
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: white 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue
      accent: white

nav:
    - Home:
        - Overview: index.md
        - Getting Started: Getting_Started.md
    - API Documentation: 
        - Documentation: Overview_Documentation.md
        - ASCOR Endpoints: Ascor_EP.md
        - Company Endpoints: Company_EP.md
        - CP Endpoints: CP_EP.md
        - MQ Endpoints: MQ_EP.md

plugins:
  - search
  - swagger-ui-tag:
      tryItOutEnabled: true
      docExpansion: none