site_name: "TPI API"
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: white 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue
      accent: white

nav:
    - Home:
        - Overview: README_V2.md
        - Getting Started: GETTING_STARTED.md
        - About API: ENDPOINTS_REVISED.md
    - API Documentation: 
        - Endpoints: test.md
